name: Opllamajs Workflow
on:
  push:
    branches:
      - master

jobs: 
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - uses: oleksiyrudenko/gha-git-credentials@v1
        with:
          name: Ali Hassan
          email: opllama2@gmail.com
          token: ${{ secrets.GH_TOKEN }}
      - run: npm ci && npm i -g lerna
      - run: npm run build
      - run: lerna publish --yes
