name: Opllamajs Workflow
on:
  push:
    branches:
      - master

jobs: 
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - run: npm ci && npm i -g lerna
      - run: npm run build
      - run: lerna publish --yes --registry https://registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
